Repository segment-oj/segmentoj-frontend, pull requests merged in 2020-08, with the labels that each got.

#75 Improve user experience ztl
  src/assets/css/basic.css
  src/assets/css/mde.css
  src/components/lib/MarkdownEditor.vue
  src/components/page/navbar.vue
  src/components/problem/content.vue
  src/components/problem/edit.vue
  src/components/user/content.vue
  src/components/user/edit.vue
  src/components/user/login.vue
  src/sfconfig.js
Labels: UX Improvements, review required

#76 Improve mobile ux & css
  package.json
  src/assets/code_mirror/tomorrow.css
  src/assets/css/basic.css
  src/assets/css/theme.css
  src/assets/element/index.css
  src/assets/fonts/fonts.css
  src/components/404.vue
  src/components/app/editor.vue
  src/components/home/carousel.vue
  src/components/home/page.vue
  src/components/lib/AjaxTable.vue
  src/components/lib/MarkdownContainer.vue
  src/components/lib/confirmDelete.vue
  src/components/lib/editor.vue
  src/components/lib/jumpToProblem.vue
  src/components/lib/tag.vue
  src/components/page/navbar.vue
  src/components/problem/content.vue
  src/components/problem/edit.vue
  src/components/problem/list.vue
  src/components/problem/listTag.vue
  src/components/problem/submit.vue
  src/components/user/content.vue
  src/components/user/edit.vue
  src/components/user/login.vue
  src/components/user/register.vue
  src/main.js
  src/message.js
  src/router.js
  src/sfconfig.js
  src/store/store.js
  src/store/tags.js
Labels: Changes Required, High Priority, enhancement

#80 Fix tag loading
  src/components/lib/AjaxTable.vue
  src/components/problem/listTag.vue
  src/methods/lock.js
  src/store/tags.js
Labels: High Priority, Performance Improvements

#82 fix showtag button
  src/components/problem/list.vue
Labels: bug

#83 update CI
  .github/workflows/lint.yml
  .github/workflows/main.yml
Labels: CI, Performance Improvements

#81 Fix bugs
  src/assets/code_mirror/tomorrow.css
  src/components/lib/problemTag.vue
  src/components/problem/content.vue
  src/components/problem/edit.vue
  src/components/problem/list.vue
  src/components/problem/listTag.vue
  src/components/user/content.vue
  src/components/user/edit.vue
Labels: Code Style, Conflict, help wanted

#84 fix user edit
  src/components/user/edit.vue
Labels: UX Improvements, bug

#85 Add search ztl
  src/StringPrototype.js
  src/components/lib/AjaxTable.vue
  src/components/lib/jumpToProblem.vue
  src/components/problem/list.vue
Labels: bug, enhancement

#87 change in api
  src/components/problem/list.vue
  src/components/user/content.vue
  src/components/user/edit.vue
Labels: Performance Improvements, bug, enhancement

#89 optimize edit problem
  src/components/problem/edit.vue
Labels: Performance Improvements, good first issue

#90 change api
  package.json
  src/components/lib/AjaxTable.vue
  src/components/problem/content.vue
  src/components/problem/edit.vue
  src/components/problem/list.vue
Labels: Performance Improvements, bug, enhancement

#92 add change password
  src/components/lib/problemTag.vue
  src/components/user/changePassword.vue
  src/components/user/register.vue
  src/router.js
Labels: enhancement, review required

#91 improved problem list style
  src/assets/css/basic.css
  src/components/lib/AjaxTable.vue
  src/components/lib/jumpToProblem.vue
  src/components/problem/create.vue
  src/components/problem/list.vue
  src/components/user/login.vue
  src/store/createProblem.js
  src/store/store.js
Labels: High Priority, UX Improvements, enhancement

#94 Add lang select code mirror ztl
  src/assets/code_mirror/CodeMirror.css
  src/assets/code_mirror/ayu-mirage.css
  src/assets/code_mirror/monokai.css
  src/assets/code_mirror/neo.css
  src/assets/code_mirror/tomorrow.css
  src/assets/code_mirror/zenburn.css
  src/components/app/editor.vue
  src/components/lib/editor.vue
  src/components/problem/create.vue
  src/components/problem/submit.vue
  src/sfconfig.js
Labels: UX Improvements, enhancement

#95 Fix bugs ztl
  src/assets/code_mirror/ayu-mirage.css
  src/assets/code_mirror/monokai.css
  src/assets/code_mirror/tomorrow.css
  src/components/lib/problemTag.vue
  src/components/problem/list.vue
  src/sfconfig.js
Labels: Code Style, UX Improvements, bug, enhancement, good first issue

#93 Add status list
  src/assets/css/basic.css
  src/assets/css/theme.css
  src/components/page/navbar.vue
  src/components/problem/ProblemTitleLink.vue
  src/components/problem/list.vue
  src/components/status/list.vue
  src/components/user/UserNameLink.vue
  src/router.js
  src/sfconfig.js
Labels: UX Improvements, enhancement

#96 fix problem list bug
  src/components/problem/list.vue
Labels: bug, good first issue
