Repository segment-oj/segmentoj-frontend, pull requests merged in 2020-09, with the labels that each got.

#101 add static site upload ci
  .github/workflows/tencent-dev.yml
Labels: CI/CD

#105 remove unused request
  README.md
  src/components/problem/list.vue
  src/components/status/list.vue
Labels: bug, review required

#106 fix status bug
  src/components/status/list.vue
Labels: bug, review required

#108 fix CI on static site
  .github/workflows/tencent-dev.yml
Labels: CI/CD, bug
