Repository segment-oj/segmentoj-frontend, pull requests merged in 2020-11, with the labels that each got.

#112 Fix CI node version
  .github/workflows/lint.yml
Labels: CI/CD, bug

#113 update CI
  .github/workflows/lint-pr.yml
  .github/workflows/lint-push.yml
Labels: CI/CD, enhancement

#114 [fix] CI max-parallel
  .github/workflows/lint-pr.yml
  .github/workflows/lint-push.yml
Labels: CI/CD, bug

#115 [feature] new user page
  src/components/lib/MarkdownEditor.vue
  src/components/user/content.vue
  src/components/user/edit.vue
  src/components/user/information.vue
  src/components/user/secure.vue
  src/router.js
Labels: UX Improvements, bug, enhancement

#117 [lint] fix code style and spelling
  src/components/user/content.vue
Labels: Code Style

#118 [fix] fix markdown editor tab bug
  src/components/lib/MarkdownEditor.vue
Labels: bug

#119 [feature] Add avatar component
  src/components/page/navbar.vue
  src/components/user/avatar.vue
  src/components/user/content.vue
Labels: UX Improvements, enhancement

#120 [refactory*] drop mess code and fix legency bugs
  deploy.sh
  package.json
  src/App.vue
  src/components/account/ChangePassword.vue
  src/components/account/UserNameLink.vue
  src/components/account/avatar.vue
  src/components/account/content.vue
  src/components/account/edit.vue
  src/components/account/information.vue
  src/components/account/login.vue
  src/components/account/logout.vue
  src/components/account/register.vue
  src/components/account/secure.vue
  src/components/home/page.vue
  src/components/lib/AjaxTable.vue
  src/components/lib/ConfirmDelete.vue
  src/components/lib/JumpToProblem.vue
  src/components/lib/ProblemTag.vue
  src/components/lib/SelectTag.vue
  src/components/page/navbar.vue
  src/components/problem/EditTag.vue
  src/components/problem/ListTag.vue
  src/components/problem/content.vue
  src/components/problem/create.vue
  src/components/problem/edit.vue
  src/components/problem/list.vue
  src/components/problem/submit.vue
  src/components/status/content.vue
  src/components/status/list.vue
  src/main.js
  src/methods/message.js
  src/methods/string.js
  src/router.js
  src/store/CreateProblem.js
  src/store/TagEdit.js
  src/store/store.js
Labels: Code Style/Refactory, UX Improvements, bug

#123 [fix] normal user status resubmit
  src/components/status/content.vue
Labels: UX Improvements, bug

#124 [feature] Add nav color
  .gitignore
  src/assets/code_mirror/ayu-mirage.css
  src/assets/code_mirror/monokai.css
  src/assets/code_mirror/neo.css
  src/assets/element/index.css
  src/components/account/edit.vue
  src/components/account/login.vue
  src/components/page/navbar.vue
  src/store/user.js
Labels: UX Improvements, enhancement

#126 [feature] add linked buttons
  src/components/problem/edit.vue
  src/components/problem/submit.vue
  src/components/status/content.vue
Labels: UX Improvements, enhancement
