Repository segment-oj/segmentoj-frontend, pull requests merged in 2021-02, with the labels that each got.

#140 [arch] add package-lock.json
  package-lock.json
Labels: bug

#142 [fix] change npm registry to the origin
  package-lock.json
Labels: CI/CD, bug

#143 [feature] CI for auto rebase PR
  .github/workflows/auto-rebase.yml
Labels: CI/CD, enhancement

#150 [feature] add account edit submit button at the bottom
  src/components/account/edit.vue
Labels: UX Improvements, enhancement

#155 [fix] reconstruct problem content
  src/assets/css/basic.css
  src/components/problem/content.vue
Labels: UX Improvements, bug, enhancement

#161 [fix] problem content expand button
  src/components/problem/content.vue
Labels: bug

#166 [improve] add last edit
  src/components/problem/content.vue
Labels: enhancement

#167 [feature] add status list search
  src/components/status/list.vue
Labels: enhancement

#168 [feature] add status list search button
  src/components/status/list.vue
Labels: enhancement

#169 [fix] tag url string format
  src/components/lib/SelectTag.vue
Labels: bug

#171 [feature] code mirror in problem submit
  src/components/app/CodeEditor.vue
  src/components/lib/MarkdownEditor.vue
  src/components/lib/editor.vue
  src/components/problem/submit.vue
  src/sfconfig.js
Labels: UX Improvements, enhancement
